# nginx/nginx.conf
events {
    worker_connections 4096;
}

http {
    # Use Docker's internal DNS resolver so NGINX re-resolves worker-direct
    # on each request
    resolver 127.0.0.11 valid=10s ipv6=off;

    # change to direct workers ips
    # upstream backend_servers {
    #     server 192.168.1.10:8000;
    #     server 192.168.1.11:8000;
    # }

    server {
        listen 80;

        location / {
            # forces DNS re-resolution via the resolver,
            # enabling round-robin across all worker-direct replicas.
            
            set $backend http://worker-direct:8000;
            # set $backend http://backend_servers;
            proxy_pass $backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_connect_timeout 10s;
            proxy_read_timeout 30s;
        }
    }
}